# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dag_new <- function() {
    .Call(`_pipeflow_dag_new`)
}

dag_clone <- function(dp) {
    .Call(`_pipeflow_dag_clone`, dp)
}

dag_size <- function(dp) {
    .Call(`_pipeflow_dag_size`, dp)
}

dag_get_min_id <- function(dp) {
    .Call(`_pipeflow_dag_get_min_id`, dp)
}

dag_get_max_id <- function(dp) {
    .Call(`_pipeflow_dag_get_max_id`, dp)
}

dag_has_edge <- function(dp, from, to) {
    .Call(`_pipeflow_dag_has_edge`, dp, from, to)
}

dag_has_node <- function(dp, id) {
    .Call(`_pipeflow_dag_has_node`, dp, id)
}

dag_has_dangling_node <- function(dp) {
    .Call(`_pipeflow_dag_has_dangling_node`, dp)
}

dag_is_cyclic <- function(dp) {
    .Call(`_pipeflow_dag_is_cyclic`, dp)
}

dag_is_tidy <- function(dp) {
    .Call(`_pipeflow_dag_is_tidy`, dp)
}

dag_get_outgoing <- function(dp, id) {
    .Call(`_pipeflow_dag_get_outgoing`, dp, id)
}

dag_get_incoming <- function(dp, id) {
    .Call(`_pipeflow_dag_get_incoming`, dp, id)
}

dag_get_nodes_order <- function(dp) {
    .Call(`_pipeflow_dag_get_nodes_order`, dp)
}

dag_get_dangling_nodes <- function(dp) {
    .Call(`_pipeflow_dag_get_dangling_nodes`, dp)
}

dag_get_reachable_nodes_down <- function(dp, start_ids) {
    .Call(`_pipeflow_dag_get_reachable_nodes_down`, dp, start_ids)
}

dag_get_reachable_nodes_up <- function(dp, start_ids) {
    .Call(`_pipeflow_dag_get_reachable_nodes_up`, dp, start_ids)
}

dag_add_node <- function(dp) {
    .Call(`_pipeflow_dag_add_node`, dp)
}

dag_add_node_at <- function(dp, pos) {
    .Call(`_pipeflow_dag_add_node_at`, dp, pos)
}

dag_add_edge <- function(dp, from, to) {
    .Call(`_pipeflow_dag_add_edge`, dp, from, to)
}

dag_add_edges <- function(dp, from, to) {
    .Call(`_pipeflow_dag_add_edges`, dp, from, to)
}

dag_add_edges_to <- function(dp, from, to) {
    .Call(`_pipeflow_dag_add_edges_to`, dp, from, to)
}

dag_add_dag <- function(dp, other_dp) {
    .Call(`_pipeflow_dag_add_dag`, dp, other_dp)
}

dag_remove_node <- function(dp, id, force = FALSE) {
    .Call(`_pipeflow_dag_remove_node`, dp, id, force)
}

dag_remove_edge <- function(dp, from, to, force = FALSE) {
    .Call(`_pipeflow_dag_remove_edge`, dp, from, to, force)
}

dag_tidy_up <- function(dp) {
    invisible(.Call(`_pipeflow_dag_tidy_up`, dp))
}

dag_rebuild <- function(dp) {
    .Call(`_pipeflow_dag_rebuild`, dp)
}

dag_shift <- function(dp, offset) {
    invisible(.Call(`_pipeflow_dag_shift`, dp, offset))
}

